### ISSUE TITLE
Can't add unit to Delphi 5 project.

### ISSUE THREAD

**Issue by dtpfl** [ahausladen/AsyncCalls#2]
Delphi: Version 5.0 (6.18) Update Pack 1
OS: Windows 10 1809 (Build 17763.379)

_"Add the AsyncCalls.pas unit to your project's uses-clause."_
Issue: When i add AsyncCalls.pas into the uses-clause the compiler  throws following error:
DE: Zeile zu lang (mehr als 1023 Zeichen)
EN: Line too long (more then 1023 letters)

**Comment by ahausladen** [comment]
You've downloaded the file with Linux line breaks (LF) instead of Windows line breaks (CRLF). Delphi 5's compiler doesn't understand Linux line breaks.
