### ISSUE TITLE
the project does not compile

### ISSUE THREAD

**Issue by Avoron007** [ahausladen/AsyncCalls#4]
I downloaded the file AsyncCalls.pas but the project does not compile
delphi 10.2
16 Error:

Undeclared identifier 'ExecuteAsync' at line 3192 (3192:50)

Identifier redeclared 'TAsyncCalls.Invoke' at line 3195 (3195:16)

Undeclared identifier 'ExecuteAsync' at line 3201 (3201:57)

Undeclared identifier 'ExecuteAsync' at line 3210 (3210:62)

Identifier redeclared 'TAsyncCalls.Invoke' at line 3213 (3213:16)

Undeclared identifier 'ExecuteAsync' at line 3219 (3219:69)

Undeclared identifier 'ExecuteAsync' at line 3228 (3228:72)

Identifier redeclared 'TAsyncCalls.Invoke' at line 3231 (3231:16)

Undeclared identifier 'ExecuteAsync' at line 3237 (3237:79)

Undeclared identifier 'ExecuteAsync' at line 3246 (3246:82)

Identifier redeclared 'TAsyncCalls.Invoke' at line 3249 (3249:16)

Undeclared identifier 'ExecuteAsync' at line 3255 (3255:89)

Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND at line 58 (58:5)

Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND at line 62 (62:5)

Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND at line 66 (66:5)

Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND at line 70 (70:5)

what to do?

**Comment by ahausladen** [comment]
It compiles just fine with Delphi 10.2. Only the IDE's ErrorInsight that was and is still broken since the very first Delphi release it was introduced (Delphi 8) has problems. The compiler has no problems to compile the code.
